name: Build do MVP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obter código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compilar aplicação
        run: sh build.sh

      - name: Verificar JAR gerado
        run: test -f dist/GestaoToner-Academico.jar
